### ISSUE TITLE
create react appする

### ISSUE THREAD

**Issue by fumiyanll23** [math-eng-seminar/mahjonganal#1]

**Comment by fumiyanll23** [comment]
[チュートリアル：React の導入/チュートリアルの準備/オプション 2: ローカル開発環境](https://ja.reactjs.org/tutorial/tutorial.html#setup-option-2-local-development-environment) を終える

**Comment by fumiyanll23** [comment]
:done:

**Comment by rbakkkam** [comment]
closeしますね
